/*!
 * @file bare.h
 * @brief Entry point and intialisation declrations for the bare extention.
 */
#ifndef _METERPRETER_SOURCE_EXTENSION_NINJASPLOIT_NINJASPLOIT_H
#define _METERPRETER_SOURCE_EXTENSION_NINJASPLOIT_NINJASPLOIT_H

#define TLV_TYPE_EXTENSION_NINJASPLOIT	0


#define TLV_TYPE_NINJASPLOIT_INSTALL_HOOKS MAKE_CUSTOM_TLV(TLV_META_TYPE_STRING,	TLV_TYPE_EXTENSION_NINJASPLOIT,	TLV_EXTENSIONS + 1)
#define TLV_TYPE_NINJASPLOIT_RESTORE_HOOKS MAKE_CUSTOM_TLV(TLV_META_TYPE_STRING,	TLV_TYPE_EXTENSION_NINJASPLOIT,	TLV_EXTENSIONS + 2)
// Custom TLVs go here

#endif
